name: Telegram Notifier

on:
  push:
    branches:
      - improve-ci

jobs:
  notify:
    name: Notify via Telegram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Message creator
        run: |
          before=${{github.event.before}}
          after=${{github.event.after}}
          commits=${{github.event.commits}}
          echo ${{github.event.commits}}
          echo ${{github.event.commits[0]}}
          echo ${{github.event.commits[0].id}}
          echo ${{github.event.commits[0].message}}
          echo ${{github.event.commits[0].url}}
          echo ${#commits[@]}
          echo ${{toJson($(commits))}}
          for n in ${commits} ; do
            echo $n
            echo ${n.message}
          done

      - name: Send message to Telegram
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: -1001575459251
          token: 5285147386:AAE6dVJcU5eyNODmI2f-6iZb7QeauajBc70
          disable_web_page_preview: true
          format: html
          message: |
            <a href="github.com/${{github.repository}}/commit/${{github.sha}}">${{github.sha}}</a> • <a href="github.com/${{github.actor}}">${{github.actor}}</a>
            commits=${{github.event.commits}}
            
            ${{ github.event.commits[0].message }}
            @Kindnesswall_Android_App
            ⚡️ <a href="https://github.com/aszenz/repo/commit/${{ github.event.push.after }}">Commits</a> pushed to master by <em>${{ github.event.push.pusher.name }}</em> ⚡️
            ${{ github.actor }}:${{ github.event.head_commit.message }}

      - name: send message using with
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: -1001575459251
          token: 5285147386:AAE6dVJcU5eyNODmI2f-6iZb7QeauajBc70
          message: |
            The ${{ github.event_name }} event triggered second step.
            show the github variable ref: ${{ github.ref }}
            show the github variable commit: ${{ github.sha }}
            show the github variable ref: {{ commit.ref }}
            show the github variable commit: {{ commit.sha }}
            Commit Message: ${{ github.event.head_commit.message }}
